apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image:  nginx
    env:
    - name: coiurse
      valueFrom:
        configMapKeyRef:
          name: daws78s
          key:  course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: daws78s
          key:  trainer     

