apiVersion: v1
kind: service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
  labels: 
    name: frontend
    project: expense
    component: frontend
    environmrnt: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodeport: 32760
 