apiVersion: v1
kind: service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    name: frontend
    project: expense
    component: frontend
    environmrnt: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodeport: 32761
 